language: python
python:
  - "2.7"
  - "3.7"

# allow py3 to fail due to no required MySQLdb-python module.
matrix:
  allow_failures:
    - python: "3.7"

install:
  - pip install -r requirements.txt

git:
  depth: 1

before_install: pip install --upgrade pip
install: pip install flake8 pytest -r requirements.txt

before_script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

# Running unittests requires a fully-working iRedMail server.
script:
  - cd tests/
#  - bash main.sh
