language: python

# Use Ubuntu 18.04 (bionic) for testing, 16.04 is not supported by iRedMail.
#dist: bionic

# We need to run this program on different Linux/BSD distributions, each ships
# different Python versions.
python:
  - "3.4"  # CentOS 7
  - "3.5"  # Debian 9
  - "3.6"  # Ubuntu 18.04
  - "3.7"  # Debian 10

addons:
  apt:
    update: true
    packages:
      - mlmmj
      - uwsgi
      - uwsgi-plugin-python3

before_install:
  - pip install --upgrade pip
  - sudo mkdir -p /var/vmail
  - sudo chmod 0755 /var/vmail
  - sudo groupadd mlmmj
  - sudo useradd -m -g mlmmj -d /var/vmail/mlmmj -s /sbin/nologin mlmmj
  - sudo mkdir -p /var/vmail/mlmmj-archive
  - sudo chown -R mlmmj:mlmmj /var/vmail/mlmmj /var/vmail/mlmmj-archive
  - sudo chmod -R 0700 /var/vmail/mlmmj /var/vmail/mlmmj-archive
  - sudo cp settings.py.sample settings.py
  # hack for travis-ci. it must be 0400 on production server.
  - sudo chmod 0777 settings.py
  - sudo echo 'backend_api = "bk_none"' >> settings.py
  - sudo echo 'backend_cli = "bk_none"' >> settings.py
  - sudo echo 'api_auth_tokens = ["b7bc9c619ca13bd09ef90f5f65e17d68"]' >> settings.py
  - sudo echo 'MLMMJ_SPOOL_DIR = "/var/vmail/mlmmj"' >> settings.py
  - sudo echo 'MLMMJ_ARCHIVE_DIR = "/var/vmail/mlmmj-archive"' >> settings.py

  - git clone --depth=1 https://github.com/webpy/webpy.git
  - cp -rf webpy/web .

install:
  - pip install flake8 -r requirements.txt
  - python3 -c "import web; print(web.__version__); print(web.__file__)"

before_script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - uwsgi_python3 --plugins=python --http-socket=127.0.0.1:7790 --wsgi-file mlmmjadmin.py --callable application --uid root --threads 2 &
  - sleep 3

script:
  - cd tests/
  - py.test -s -x test_mlmmj.py
